import type { Meal } from "@/lib/types";

const UNSPLASH = (id: string) =>
  `https://images.unsplash.com/${id}?w=800&q=80&auto=format`;

const FOODISH = (category: string, n = 1) =>
  `https://foodish-api.com/images/${category}/${category}${n}.jpg`;

/** Curated deck — Foodish when category matches the dish; verified Unsplash IDs otherwise. */
export const SEED_MEALS: Meal[] = [
  {
    id: "seed-grilled-chicken-salad",
    name: "Grilled Chicken Salad",
    imageUri: UNSPLASH("photo-1546069901-ba9599a7e63c"),
    difficulty: 2,
    price: 3,
    highProtein: true,
    highVegetables: true,
    requiredEquipment: ["stovetop"],
    containsMeat: true,
    estimatedMinutes: 25,
    ingredients: [
      "chicken breast",
      "mixed greens",
      "cherry tomatoes",
      "cucumber",
      "olive oil",
      "lemon",
      "salt",
      "pepper",
    ],
  },
  {
    id: "seed-pasta-carbonara",
    name: "Pasta Carbonara",
    imageUri: FOODISH("pasta", 1),
    difficulty: 3,
    price: 3,
    highProtein: true,
    highVegetables: false,
    requiredEquipment: ["stovetop"],
    containsMeat: true,
    estimatedMinutes: 30,
    ingredients: [
      "spaghetti",
      "eggs",
      "pecorino cheese",
      "guanciale or bacon",
      "black pepper",
      "salt",
    ],
  },
  {
    id: "seed-veggie-stir-fry",
    name: "Vegetable Stir Fry",
    imageUri: UNSPLASH("photo-1512058564366-18510be2db19"),
    difficulty: 2,
    price: 2,
    highProtein: false,
    highVegetables: true,
    requiredEquipment: ["stovetop"],
    containsMeat: false,
    estimatedMinutes: 25,
    ingredients: [
      "broccoli",
      "bell pepper",
      "carrot",
      "snap peas",
      "garlic",
      "ginger",
      "soy sauce",
      "sesame oil",
      "rice",
    ],
  },
  {
    id: "seed-salmon-rice",
    name: "Baked Salmon & Rice",
    imageUri: UNSPLASH("photo-1467003909585-2f8a72700288"),
    difficulty: 3,
    price: 4,
    highProtein: true,
    highVegetables: false,
    requiredEquipment: ["oven", "stovetop"],
    containsMeat: true,
    estimatedMinutes: 40,
    ingredients: [
      "salmon fillet",
      "jasmine rice",
      "lemon",
      "dill",
      "olive oil",
      "garlic",
      "salt",
      "pepper",
    ],
  },
  {
    id: "seed-burrito-bowl",
    name: "Bean Burrito Bowl",
    imageUri: UNSPLASH("photo-1512621776951-a57141f2eefd"),
    difficulty: 2,
    price: 2,
    highProtein: true,
    highVegetables: true,
    requiredEquipment: ["stovetop"],
    containsMeat: false,
    estimatedMinutes: 20,
    ingredients: [
      "black beans",
      "brown rice",
      "corn",
      "lettuce",
      "salsa",
      "avocado",
      "lime",
      "cilantro",
    ],
  },
  {
    id: "seed-margherita-pizza",
    name: "Margherita Pizza",
    imageUri: FOODISH("pizza", 1),
    difficulty: 3,
    price: 3,
    highProtein: false,
    highVegetables: false,
    requiredEquipment: ["oven"],
    containsMeat: false,
    estimatedMinutes: 35,
    ingredients: [
      "pizza dough",
      "tomato sauce",
      "fresh mozzarella",
      "basil",
      "olive oil",
      "salt",
    ],
  },
  {
    id: "seed-yogurt-parfait",
    name: "Greek Yogurt Parfait",
    imageUri: UNSPLASH("photo-1488477181946-6428a0291777"),
    difficulty: 1,
    price: 2,
    highProtein: true,
    highVegetables: false,
    requiredEquipment: [],
    containsMeat: false,
    estimatedMinutes: 5,
    ingredients: ["greek yogurt", "granola", "berries", "honey", "chia seeds"],
  },
  {
    id: "seed-lentil-soup",
    name: "Red Lentil Soup",
    imageUri: UNSPLASH("photo-1547592166-23ac45744acd"),
    difficulty: 2,
    price: 1,
    highProtein: true,
    highVegetables: true,
    requiredEquipment: ["stovetop"],
    containsMeat: false,
    estimatedMinutes: 35,
    ingredients: [
      "red lentils",
      "onion",
      "carrot",
      "celery",
      "cumin",
      "vegetable broth",
      "olive oil",
      "salt",
    ],
  },
  {
    id: "seed-steak-potatoes",
    name: "Steak & Roasted Potatoes",
    imageUri: UNSPLASH("photo-1555939594-58d7cb561ad1"),
    difficulty: 4,
    price: 5,
    highProtein: true,
    highVegetables: false,
    requiredEquipment: ["oven", "stovetop"],
    containsMeat: true,
    estimatedMinutes: 50,
    ingredients: [
      "ribeye or sirloin steak",
      "yukon potatoes",
      "butter",
      "rosemary",
      "garlic",
      "salt",
      "pepper",
    ],
  },
  {
    id: "seed-caprese-salad",
    name: "Caprese Salad",
    imageUri: UNSPLASH("photo-1592417817098-8fd3d9eb14a5"),
    difficulty: 1,
    price: 3,
    highProtein: false,
    highVegetables: true,
    requiredEquipment: [],
    containsMeat: false,
    estimatedMinutes: 10,
    ingredients: [
      "tomatoes",
      "fresh mozzarella",
      "basil",
      "balsamic glaze",
      "olive oil",
      "salt",
    ],
  },
  {
    id: "seed-tuna-poke",
    name: "Tuna Poke Bowl",
    imageUri: UNSPLASH("photo-1544025162-d76694265947"),
    difficulty: 3,
    price: 4,
    highProtein: true,
    highVegetables: false,
    requiredEquipment: ["stovetop"],
    containsMeat: true,
    estimatedMinutes: 30,
    ingredients: [
      "sushi-grade tuna",
      "sushi rice",
      "soy sauce",
      "sesame oil",
      "cucumber",
      "avocado",
      "nori",
      "green onion",
    ],
  },
  {
    id: "seed-vegetable-curry",
    name: "Vegetable Coconut Curry",
    imageUri: FOODISH("butter-chicken", 2),
    difficulty: 3,
    price: 2,
    highProtein: false,
    highVegetables: true,
    requiredEquipment: ["stovetop"],
    containsMeat: false,
    estimatedMinutes: 35,
    ingredients: [
      "coconut milk",
      "curry paste",
      "cauliflower",
      "chickpeas",
      "spinach",
      "onion",
      "garlic",
      "rice",
    ],
  },
  {
    id: "seed-ramen-bowl",
    name: "Quick Ramen Bowl",
    imageUri: UNSPLASH("photo-1551183053-bf91a1d81141"),
    difficulty: 2,
    price: 2,
    highProtein: true,
    highVegetables: false,
    requiredEquipment: ["stovetop"],
    containsMeat: false,
    estimatedMinutes: 15,
    ingredients: [
      "ramen noodles",
      "soft-boiled egg",
      "green onion",
      "soy sauce",
      "sesame oil",
      "corn",
      "spinach",
    ],
  },
  {
    id: "seed-smash-burger",
    name: "Smash Burger",
    imageUri: FOODISH("burger", 1),
    difficulty: 2,
    price: 3,
    highProtein: true,
    highVegetables: false,
    requiredEquipment: ["stovetop"],
    containsMeat: true,
    estimatedMinutes: 20,
    ingredients: [
      "ground beef",
      "burger bun",
      "cheddar cheese",
      "lettuce",
      "tomato",
      "pickles",
      "ketchup",
    ],
  },
  {
    id: "seed-quesadilla",
    name: "Cheese Quesadilla",
    imageUri: FOODISH("pizza", 6),
    difficulty: 1,
    price: 2,
    highProtein: true,
    highVegetables: false,
    requiredEquipment: ["stovetop"],
    containsMeat: false,
    estimatedMinutes: 15,
    ingredients: [
      "flour tortillas",
      "cheddar cheese",
      "black beans",
      "salsa",
      "sour cream",
      "lime",
    ],
  },
  {
    id: "seed-pancakes",
    name: "Stack of Pancakes",
    imageUri: UNSPLASH("photo-1567620905732-2d1ec7ab7445"),
    difficulty: 1,
    price: 2,
    highProtein: false,
    highVegetables: false,
    requiredEquipment: ["stovetop"],
    containsMeat: false,
    estimatedMinutes: 20,
    ingredients: [
      "pancake mix",
      "milk",
      "egg",
      "butter",
      "maple syrup",
      "berries",
    ],
  },
  {
    id: "seed-pepperoni-pizza",
    name: "Pepperoni Pizza",
    imageUri: FOODISH("pizza", 2),
    difficulty: 2,
    price: 3,
    highProtein: true,
    highVegetables: false,
    requiredEquipment: ["oven"],
    containsMeat: true,
    estimatedMinutes: 30,
    ingredients: [
      "pizza dough",
      "tomato sauce",
      "mozzarella",
      "pepperoni",
      "oregano",
      "olive oil",
    ],
  },
  {
    id: "seed-butter-chicken",
    name: "Butter Chicken & Rice",
    imageUri: FOODISH("butter-chicken", 1),
    difficulty: 3,
    price: 3,
    highProtein: true,
    highVegetables: false,
    requiredEquipment: ["stovetop"],
    containsMeat: true,
    estimatedMinutes: 40,
    ingredients: [
      "chicken thigh",
      "tomato passata",
      "cream",
      "butter",
      "garam masala",
      "garlic",
      "basmati rice",
    ],
  },
  {
    id: "seed-avocado-toast",
    name: "Avocado Toast",
    imageUri: UNSPLASH("photo-1540189549336-e6e99c3679fe"),
    difficulty: 1,
    price: 2,
    highProtein: false,
    highVegetables: true,
    requiredEquipment: ["toaster"],
    containsMeat: false,
    estimatedMinutes: 10,
    ingredients: [
      "sourdough bread",
      "avocado",
      "lemon juice",
      "chili flakes",
      "salt",
      "pepper",
      "olive oil",
    ],
  },
  {
    id: "seed-chicken-biryani",
    name: "Chicken Biryani",
    imageUri: FOODISH("biryani", 1),
    difficulty: 3,
    price: 3,
    highProtein: true,
    highVegetables: false,
    requiredEquipment: ["stovetop"],
    containsMeat: true,
    estimatedMinutes: 45,
    ingredients: [
      "basmati rice",
      "chicken thigh",
      "onion",
      "biryani spice mix",
      "yogurt",
      "garlic",
      "ginger",
    ],
  },
  {
    id: "seed-spaghetti-bolognese",
    name: "Spaghetti Bolognese",
    imageUri: FOODISH("pasta", 2),
    difficulty: 2,
    price: 3,
    highProtein: true,
    highVegetables: false,
    requiredEquipment: ["stovetop"],
    containsMeat: true,
    estimatedMinutes: 35,
    ingredients: [
      "spaghetti",
      "ground beef",
      "tomato sauce",
      "onion",
      "garlic",
      "parmesan",
      "olive oil",
    ],
  },
  {
    id: "seed-fried-rice",
    name: "Egg Fried Rice",
    imageUri: FOODISH("rice", 1),
    difficulty: 2,
    price: 2,
    highProtein: true,
    highVegetables: true,
    requiredEquipment: ["stovetop"],
    containsMeat: false,
    estimatedMinutes: 20,
    ingredients: [
      "cooked rice",
      "eggs",
      "peas",
      "carrot",
      "soy sauce",
      "sesame oil",
      "green onion",
    ],
  },
  {
    id: "seed-samosa-snack",
    name: "Samosa Snack Plate",
    imageUri: FOODISH("samosa", 1),
    difficulty: 2,
    price: 2,
    highProtein: false,
    highVegetables: true,
    requiredEquipment: ["air_fryer", "oven"],
    containsMeat: false,
    estimatedMinutes: 25,
    ingredients: [
      "frozen samosas",
      "potato",
      "peas",
      "mint chutney",
      "tamarind sauce",
      "yogurt",
    ],
  },
  {
    id: "seed-masala-dosa",
    name: "Masala Dosa",
    imageUri: FOODISH("dosa", 1),
    difficulty: 3,
    price: 2,
    highProtein: false,
    highVegetables: true,
    requiredEquipment: ["stovetop"],
    containsMeat: false,
    estimatedMinutes: 35,
    ingredients: [
      "dosa batter",
      "potato",
      "onion",
      "mustard seeds",
      "turmeric",
      "coconut chutney",
    ],
  },
  {
    id: "seed-idly-breakfast",
    name: "Idly Breakfast",
    imageUri: FOODISH("idly", 1),
    difficulty: 2,
    price: 1,
    highProtein: false,
    highVegetables: false,
    requiredEquipment: ["stovetop"],
    containsMeat: false,
    estimatedMinutes: 30,
    ingredients: [
      "idly batter",
      "sambar",
      "coconut chutney",
      "mustard seeds",
      "curry leaves",
    ],
  },
  {
    id: "seed-veggie-pizza",
    name: "Roasted Veggie Pizza",
    imageUri: FOODISH("pizza", 4),
    difficulty: 2,
    price: 3,
    highProtein: false,
    highVegetables: true,
    requiredEquipment: ["oven"],
    containsMeat: false,
    estimatedMinutes: 30,
    ingredients: [
      "pizza dough",
      "tomato sauce",
      "mozzarella",
      "bell pepper",
      "zucchini",
      "red onion",
      "olive oil",
    ],
  },
  {
    id: "seed-chicken-wrap",
    name: "Grilled Chicken Wrap",
    imageUri: FOODISH("burger", 4),
    difficulty: 2,
    price: 3,
    highProtein: true,
    highVegetables: true,
    requiredEquipment: ["stovetop"],
    containsMeat: true,
    estimatedMinutes: 20,
    ingredients: [
      "tortilla wrap",
      "grilled chicken",
      "romaine lettuce",
      "tomato",
      "yogurt sauce",
      "cucumber",
    ],
  },
  {
    id: "seed-mixed-grill",
    name: "Mixed Grill Plate",
    imageUri: UNSPLASH("photo-1558030006-450675393462"),
    difficulty: 3,
    price: 4,
    highProtein: true,
    highVegetables: true,
    requiredEquipment: ["stovetop", "oven"],
    containsMeat: true,
    estimatedMinutes: 45,
    ingredients: [
      "chicken thigh",
      "sausage",
      "grilled vegetables",
      "herb butter",
      "lemon",
      "garlic",
      "olive oil",
    ],
  },
  {
    id: "seed-scrambled-eggs-toast",
    name: "Scrambled Eggs & Toast",
    imageUri: FOODISH("idly", 2),
    difficulty: 1,
    price: 1,
    highProtein: true,
    highVegetables: false,
    requiredEquipment: ["stovetop", "toaster"],
    containsMeat: false,
    estimatedMinutes: 10,
    ingredients: [
      "eggs",
      "bread",
      "butter",
      "salt",
      "pepper",
      "chives",
    ],
  },
  {
    id: "seed-microwave-mac",
    name: "Microwave Mac & Cheese",
    imageUri: FOODISH("pasta", 6),
    difficulty: 1,
    price: 2,
    highProtein: true,
    highVegetables: false,
    requiredEquipment: ["microwave"],
    containsMeat: false,
    estimatedMinutes: 10,
    ingredients: [
      "macaroni",
      "cheddar cheese",
      "milk",
      "butter",
      "salt",
      "pepper",
    ],
  },
  {
    id: "seed-chicken-tacos",
    name: "Chicken Tacos",
    imageUri: UNSPLASH("photo-1551504734-5ee1c4a1479b"),
    difficulty: 2,
    price: 3,
    highProtein: true,
    highVegetables: true,
    requiredEquipment: ["stovetop"],
    containsMeat: true,
    estimatedMinutes: 25,
    ingredients: [
      "chicken thigh",
      "corn tortillas",
      "lime",
      "cilantro",
      "onion",
      "salsa",
      "cumin",
      "salt",
    ],
  },
  {
    id: "seed-bean-chili",
    name: "Veggie Black Bean Chili",
    imageUri: UNSPLASH("photo-1547592166-23ac45744acd"),
    difficulty: 2,
    price: 2,
    highProtein: true,
    highVegetables: true,
    requiredEquipment: ["stovetop"],
    containsMeat: false,
    estimatedMinutes: 40,
    ingredients: [
      "black beans",
      "kidney beans",
      "diced tomatoes",
      "onion",
      "bell pepper",
      "chili powder",
      "cumin",
      "vegetable broth",
    ],
  },
  {
    id: "seed-tuna-sandwich",
    name: "Tuna Salad Sandwich",
    imageUri: FOODISH("burger", 5),
    difficulty: 1,
    price: 2,
    highProtein: true,
    highVegetables: false,
    requiredEquipment: [],
    containsMeat: true,
    estimatedMinutes: 10,
    ingredients: [
      "canned tuna",
      "mayonnaise",
      "celery",
      "bread",
      "lettuce",
      "lemon juice",
      "salt",
      "pepper",
    ],
  },
  {
    id: "seed-overnight-oats",
    name: "Overnight Oats",
    imageUri: FOODISH("dessert", 3),
    difficulty: 1,
    price: 1,
    highProtein: false,
    highVegetables: false,
    requiredEquipment: [],
    containsMeat: false,
    estimatedMinutes: 5,
    ingredients: [
      "rolled oats",
      "milk",
      "yogurt",
      "banana",
      "peanut butter",
      "honey",
      "cinnamon",
    ],
  },
  {
    id: "seed-chicken-caesar",
    name: "Chicken Caesar Salad",
    imageUri: UNSPLASH("photo-1546069901-ba9599a7e63c"),
    difficulty: 2,
    price: 3,
    highProtein: true,
    highVegetables: true,
    requiredEquipment: ["stovetop"],
    containsMeat: true,
    estimatedMinutes: 20,
    ingredients: [
      "chicken breast",
      "romaine lettuce",
      "parmesan",
      "croutons",
      "caesar dressing",
      "lemon",
      "garlic",
    ],
  },
  {
    id: "seed-beef-broccoli",
    name: "Beef & Broccoli Stir Fry",
    imageUri: UNSPLASH("photo-1512058564366-18510be2db19"),
    difficulty: 2,
    price: 3,
    highProtein: true,
    highVegetables: true,
    requiredEquipment: ["stovetop"],
    containsMeat: true,
    estimatedMinutes: 25,
    ingredients: [
      "flank steak",
      "broccoli",
      "soy sauce",
      "oyster sauce",
      "garlic",
      "ginger",
      "rice",
      "sesame oil",
    ],
  },
  {
    id: "seed-tomato-soup",
    name: "Tomato Soup & Bread",
    imageUri: UNSPLASH("photo-1547592166-23ac45744acd"),
    difficulty: 1,
    price: 2,
    highProtein: false,
    highVegetables: true,
    requiredEquipment: ["stovetop"],
    containsMeat: false,
    estimatedMinutes: 25,
    ingredients: [
      "crushed tomatoes",
      "onion",
      "garlic",
      "vegetable broth",
      "cream",
      "basil",
      "crusty bread",
      "olive oil",
    ],
  },
  {
    id: "seed-grilled-cheese",
    name: "Grilled Cheese Sandwich",
    imageUri: FOODISH("pizza", 7),
    difficulty: 1,
    price: 2,
    highProtein: true,
    highVegetables: false,
    requiredEquipment: ["stovetop"],
    containsMeat: false,
    estimatedMinutes: 10,
    ingredients: [
      "bread",
      "cheddar cheese",
      "butter",
      "tomato soup",
    ],
  },
  {
    id: "seed-shrimp-pasta",
    name: "Garlic Shrimp Pasta",
    imageUri: FOODISH("pasta", 3),
    difficulty: 3,
    price: 4,
    highProtein: true,
    highVegetables: false,
    requiredEquipment: ["stovetop"],
    containsMeat: true,
    estimatedMinutes: 30,
    ingredients: [
      "spaghetti",
      "shrimp",
      "garlic",
      "butter",
      "lemon",
      "parsley",
      "red pepper flakes",
      "olive oil",
    ],
  },
  {
    id: "seed-falafel-pita",
    name: "Falafel Pita Wrap",
    imageUri: FOODISH("samosa", 2),
    difficulty: 2,
    price: 2,
    highProtein: true,
    highVegetables: true,
    requiredEquipment: ["oven", "air_fryer"],
    containsMeat: false,
    estimatedMinutes: 30,
    ingredients: [
      "falafel",
      "pita bread",
      "hummus",
      "tomato",
      "cucumber",
      "lettuce",
      "tahini sauce",
    ],
  },
  {
    id: "seed-honey-garlic-chicken",
    name: "Honey Garlic Chicken",
    imageUri: FOODISH("butter-chicken", 3),
    difficulty: 2,
    price: 3,
    highProtein: true,
    highVegetables: false,
    requiredEquipment: ["stovetop"],
    containsMeat: true,
    estimatedMinutes: 30,
    ingredients: [
      "chicken thigh",
      "honey",
      "soy sauce",
      "garlic",
      "ginger",
      "rice",
      "green onion",
      "sesame seeds",
    ],
  },
  {
    id: "seed-chickpea-bowl",
    name: "Mediterranean Chickpea Bowl",
    imageUri: UNSPLASH("photo-1512621776951-a57141f2eefd"),
    difficulty: 2,
    price: 2,
    highProtein: true,
    highVegetables: true,
    requiredEquipment: [],
    containsMeat: false,
    estimatedMinutes: 15,
    ingredients: [
      "chickpeas",
      "cucumber",
      "tomato",
      "red onion",
      "feta cheese",
      "olive oil",
      "lemon",
      "parsley",
    ],
  },
  {
    id: "seed-pb-banana-toast",
    name: "Peanut Butter Banana Toast",
    imageUri: UNSPLASH("photo-1540189549336-e6e99c3679fe"),
    difficulty: 1,
    price: 1,
    highProtein: true,
    highVegetables: false,
    requiredEquipment: ["toaster"],
    containsMeat: false,
    estimatedMinutes: 5,
    ingredients: [
      "whole grain bread",
      "peanut butter",
      "banana",
      "honey",
      "chia seeds",
    ],
  },
  {
    id: "seed-black-bean-tacos",
    name: "Black Bean Soft Tacos",
    imageUri: UNSPLASH("photo-1551504734-5ee1c4a1479b"),
    difficulty: 1,
    price: 2,
    highProtein: true,
    highVegetables: true,
    requiredEquipment: ["stovetop"],
    containsMeat: false,
    estimatedMinutes: 15,
    ingredients: [
      "black beans",
      "flour tortillas",
      "salsa",
      "avocado",
      "lime",
      "cilantro",
      "cumin",
    ],
  },
  {
    id: "seed-roasted-chicken",
    name: "Oven Roasted Chicken Thighs",
    imageUri: FOODISH("butter-chicken", 6),
    difficulty: 2,
    price: 3,
    highProtein: true,
    highVegetables: true,
    requiredEquipment: ["oven"],
    containsMeat: true,
    estimatedMinutes: 45,
    ingredients: [
      "chicken thigh",
      "potatoes",
      "carrot",
      "olive oil",
      "rosemary",
      "garlic",
      "salt",
      "pepper",
    ],
  },
  {
    id: "seed-mushroom-risotto",
    name: "Creamy Mushroom Risotto",
    imageUri: FOODISH("pasta", 8),
    difficulty: 3,
    price: 3,
    highProtein: false,
    highVegetables: false,
    requiredEquipment: ["stovetop"],
    containsMeat: false,
    estimatedMinutes: 40,
    ingredients: [
      "arborio rice",
      "mushrooms",
      "onion",
      "vegetable broth",
      "parmesan",
      "butter",
      "white wine",
      "garlic",
    ],
  },
  {
    id: "seed-club-sandwich",
    name: "Turkey Club Sandwich",
    imageUri: FOODISH("burger", 6),
    difficulty: 1,
    price: 3,
    highProtein: true,
    highVegetables: true,
    requiredEquipment: [],
    containsMeat: true,
    estimatedMinutes: 10,
    ingredients: [
      "turkey slices",
      "bacon",
      "bread",
      "lettuce",
      "tomato",
      "mayonnaise",
      "mustard",
    ],
  },
  {
    id: "seed-sweet-potato-hash",
    name: "Sweet Potato Breakfast Hash",
    imageUri: UNSPLASH("photo-1506084868230-bb9d95c24759"),
    difficulty: 2,
    price: 2,
    highProtein: true,
    highVegetables: true,
    requiredEquipment: ["stovetop"],
    containsMeat: false,
    estimatedMinutes: 25,
    ingredients: [
      "sweet potato",
      "bell pepper",
      "onion",
      "eggs",
      "spinach",
      "olive oil",
      "paprika",
      "salt",
    ],
  },
  {
    id: "seed-buddha-bowl",
    name: "Roasted Veggie Buddha Bowl",
    imageUri: UNSPLASH("photo-1546069901-ba9599a7e63c"),
    difficulty: 2,
    price: 2,
    highProtein: false,
    highVegetables: true,
    requiredEquipment: ["oven"],
    containsMeat: false,
    estimatedMinutes: 35,
    ingredients: [
      "quinoa",
      "sweet potato",
      "chickpeas",
      "kale",
      "tahini",
      "lemon",
      "olive oil",
      "salt",
    ],
  },
  {
    id: "seed-pesto-penne",
    name: "Pesto Penne",
    imageUri: FOODISH("pasta", 5),
    difficulty: 1,
    price: 2,
    highProtein: false,
    highVegetables: true,
    requiredEquipment: ["stovetop"],
    containsMeat: false,
    estimatedMinutes: 20,
    ingredients: [
      "penne pasta",
      "basil pesto",
      "cherry tomatoes",
      "parmesan",
      "olive oil",
      "garlic",
      "salt",
    ],
  },
];
