import type { Meal } from "@/lib/types";

/** Curated starter deck — common home-cook meals with ingredient lists. */
export const SEED_MEALS: Meal[] = [
  {
    id: "seed-grilled-chicken-salad",
    name: "Grilled Chicken Salad",
    imageUri:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80&auto=format",
    difficulty: 2,
    price: 3,
    highProtein: true,
    highVegetables: true,
    ingredients: [
      "chicken breast",
      "mixed greens",
      "cherry tomatoes",
      "cucumber",
      "olive oil",
      "lemon",
      "salt",
      "pepper",
    ],
  },
  {
    id: "seed-pasta-carbonara",
    name: "Pasta Carbonara",
    imageUri:
      "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80&auto=format",
    difficulty: 3,
    price: 3,
    highProtein: true,
    highVegetables: false,
    ingredients: [
      "spaghetti",
      "eggs",
      "pecorino cheese",
      "guanciale or bacon",
      "black pepper",
      "salt",
    ],
  },
  {
    id: "seed-veggie-stir-fry",
    name: "Vegetable Stir Fry",
    imageUri:
      "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&q=80&auto=format",
    difficulty: 2,
    price: 2,
    highProtein: false,
    highVegetables: true,
    ingredients: [
      "broccoli",
      "bell pepper",
      "carrot",
      "snap peas",
      "garlic",
      "ginger",
      "soy sauce",
      "sesame oil",
      "rice",
    ],
  },
  {
    id: "seed-salmon-rice",
    name: "Baked Salmon & Rice",
    imageUri:
      "https://images.unsplash.com/photo-1519708227418-c8fd9a32b9a2?w=800&q=80&auto=format",
    difficulty: 3,
    price: 4,
    highProtein: true,
    highVegetables: false,
    ingredients: [
      "salmon fillet",
      "jasmine rice",
      "lemon",
      "dill",
      "olive oil",
      "garlic",
      "salt",
      "pepper",
    ],
  },
  {
    id: "seed-burrito-bowl",
    name: "Bean Burrito Bowl",
    imageUri:
      "https://images.unsplash.com/photo-1626700051175-6811733b4ccd?w=800&q=80&auto=format",
    difficulty: 2,
    price: 2,
    highProtein: true,
    highVegetables: true,
    ingredients: [
      "black beans",
      "brown rice",
      "corn",
      "lettuce",
      "salsa",
      "avocado",
      "lime",
      "cilantro",
    ],
  },
  {
    id: "seed-margherita-pizza",
    name: "Margherita Pizza",
    imageUri:
      "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&q=80&auto=format",
    difficulty: 3,
    price: 3,
    highProtein: false,
    highVegetables: false,
    ingredients: [
      "pizza dough",
      "tomato sauce",
      "fresh mozzarella",
      "basil",
      "olive oil",
      "salt",
    ],
  },
  {
    id: "seed-yogurt-parfait",
    name: "Greek Yogurt Parfait",
    imageUri:
      "https://images.unsplash.com/photo-1482049010347-93d5853e4f72?w=800&q=80&auto=format",
    difficulty: 1,
    price: 2,
    highProtein: true,
    highVegetables: false,
    ingredients: ["greek yogurt", "granola", "berries", "honey", "chia seeds"],
  },
  {
    id: "seed-lentil-soup",
    name: "Red Lentil Soup",
    imageUri:
      "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80&auto=format",
    difficulty: 2,
    price: 1,
    highProtein: true,
    highVegetables: true,
    ingredients: [
      "red lentils",
      "onion",
      "carrot",
      "celery",
      "cumin",
      "vegetable broth",
      "olive oil",
      "salt",
    ],
  },
  {
    id: "seed-steak-potatoes",
    name: "Steak & Roasted Potatoes",
    imageUri:
      "https://images.unsplash.com/photo-1546834366-cc45f8e79a55?w=800&q=80&auto=format",
    difficulty: 4,
    price: 5,
    highProtein: true,
    highVegetables: false,
    ingredients: [
      "ribeye or sirloin steak",
      "yukon potatoes",
      "butter",
      "rosemary",
      "garlic",
      "salt",
      "pepper",
    ],
  },
  {
    id: "seed-caprese-salad",
    name: "Caprese Salad",
    imageUri:
      "https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?w=800&q=80&auto=format",
    difficulty: 1,
    price: 3,
    highProtein: false,
    highVegetables: true,
    ingredients: [
      "tomatoes",
      "fresh mozzarella",
      "basil",
      "balsamic glaze",
      "olive oil",
      "salt",
    ],
  },
  {
    id: "seed-tuna-poke",
    name: "Tuna Poke Bowl",
    imageUri:
      "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80&auto=format",
    difficulty: 3,
    price: 4,
    highProtein: true,
    highVegetables: false,
    ingredients: [
      "sushi-grade tuna",
      "sushi rice",
      "soy sauce",
      "sesame oil",
      "cucumber",
      "avocado",
      "nori",
      "green onion",
    ],
  },
  {
    id: "seed-vegetable-curry",
    name: "Vegetable Coconut Curry",
    imageUri:
      "https://images.unsplash.com/photo-1585937421612-8a816856843a?w=800&q=80&auto=format",
    difficulty: 3,
    price: 2,
    highProtein: false,
    highVegetables: true,
    ingredients: [
      "coconut milk",
      "curry paste",
      "cauliflower",
      "chickpeas",
      "spinach",
      "onion",
      "garlic",
      "rice",
    ],
  },
];
