import type { MealCard } from "./types";

export const SWIPE_DECK_MEALS: MealCard[] = [
  {
    id: "deck-1",
    name: "Chicken rice bowl",
    tags: ["high protein", "cheap", "meal prep friendly"],
    estimatedTime: "25 min",
    difficulty: "Easy",
    mainIngredients: ["chicken breast", "rice", "frozen vegetables"],
    requiredAppliance: "stove",
    nutritionEstimate: "~450 kcal",
  },
  {
    id: "deck-2",
    name: "Pork pasta",
    tags: ["quick", "beginner friendly", "low effort"],
    estimatedTime: "20 min",
    difficulty: "Easy",
    mainIngredients: ["pork", "pasta", "tomato sauce"],
    requiredAppliance: "stove",
    nutritionEstimate: "~520 kcal",
  },
  {
    id: "deck-3",
    name: "Beef rice bowl",
    tags: ["high protein", "meal prep friendly"],
    estimatedTime: "30 min",
    difficulty: "Medium",
    mainIngredients: ["ground beef", "rice", "soy sauce"],
    requiredAppliance: "stove",
    nutritionEstimate: "~480 kcal",
  },
  {
    id: "deck-4",
    name: "Egg breakfast wrap",
    tags: ["quick", "cheap", "beginner friendly"],
    estimatedTime: "12 min",
    difficulty: "Easy",
    mainIngredients: ["eggs", "tortillas", "cheese"],
    requiredAppliance: "stove",
    nutritionEstimate: "~320 kcal",
  },
  {
    id: "deck-5",
    name: "Turkey sandwich",
    tags: ["low effort", "quick"],
    estimatedTime: "10 min",
    difficulty: "Easy",
    mainIngredients: ["turkey slices", "bread", "lettuce"],
    requiredAppliance: "none",
    nutritionEstimate: "~350 kcal",
  },
  {
    id: "deck-6",
    name: "Tuna rice bowl",
    tags: ["high protein", "cheap", "quick"],
    estimatedTime: "15 min",
    difficulty: "Easy",
    mainIngredients: ["canned tuna", "rice", "soy sauce"],
    requiredAppliance: "microwave",
    nutritionEstimate: "~400 kcal",
  },
  {
    id: "deck-7",
    name: "Greek yogurt bowl",
    tags: ["high protein", "quick", "low effort"],
    estimatedTime: "5 min",
    difficulty: "Easy",
    mainIngredients: ["greek yogurt", "berries", "granola"],
    requiredAppliance: "none",
    nutritionEstimate: "~280 kcal",
  },
  {
    id: "deck-8",
    name: "Chicken quesadilla",
    tags: ["quick", "beginner friendly"],
    estimatedTime: "18 min",
    difficulty: "Easy",
    mainIngredients: ["chicken breast", "tortillas", "cheese"],
    requiredAppliance: "stove",
    nutritionEstimate: "~420 kcal",
  },
  {
    id: "deck-9",
    name: "Bean burrito bowl",
    tags: ["cheap", "vegetarian", "meal prep friendly"],
    estimatedTime: "22 min",
    difficulty: "Easy",
    mainIngredients: ["black beans", "rice", "salsa"],
    requiredAppliance: "microwave",
    nutritionEstimate: "~380 kcal",
  },
  {
    id: "deck-10",
    name: "Salmon potato plate",
    tags: ["high protein", "healthy"],
    estimatedTime: "35 min",
    difficulty: "Medium",
    mainIngredients: ["salmon", "potatoes", "broccoli"],
    requiredAppliance: "oven",
    nutritionEstimate: "~510 kcal",
  },
  {
    id: "deck-11",
    name: "Tofu stir fry",
    tags: ["vegetarian", "budget-friendly", "quick"],
    estimatedTime: "20 min",
    difficulty: "Easy",
    mainIngredients: ["tofu", "frozen vegetables", "soy sauce"],
    requiredAppliance: "stove",
    nutritionEstimate: "~340 kcal",
  },
  {
    id: "deck-12",
    name: "Breakfast oats",
    tags: ["cheap", "meal prep friendly", "low effort"],
    estimatedTime: "8 min",
    difficulty: "Easy",
    mainIngredients: ["oats", "milk", "banana"],
    requiredAppliance: "microwave",
    nutritionEstimate: "~300 kcal",
  },
];
